/*------------------------------------------------------------
--------------------------------------------------------------
Exercice 2 :
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
--------------------------------------------------------------
------------------------------------------------------------*/

//Includes
#include <stdio.h>

//Defines
#define FIRST_NUMBER 1
#define SECOND_NUMBER 2
#define MAX_NUMBER 4000000

int main(int argc, char *argv[])
{
    int first_number=FIRST_NUMBER;
    int second_number=SECOND_NUMBER;
    int result=0;
    int i;

    for(i=first_number;i<MAX_NUMBER;i=second_number)
    {
	//Buffer to keep the value of the first_number
	int buf_old_first_number = first_number;

	//if the number is even we add it to the result
	if(isEven(second_number)==1)
	    result+=second_number;
        
	//Put the new value for each variables
	first_number = second_number;
	second_number += buf_old_first_number;

    }

    printf("%d", result);

    return result;
}

/*
Return 1 if it is even or return 0
*/
int isEven(int aNumber)
{
    if(aNumber%2==0)
	return 1;
    else
	return 0;
}

